name: Deploy Laravel App to (Staging) VPS Server

on:
  push:
    branches:
      - staging
  # pull_request:
  #   branches:
  #     - staging

  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [staging]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Optional inputs can be defined here
    # inputs:
    #   example_input:
    #     description: 'A description for the input'
    #     required: true
    #     default: 'default_value'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}

      - name: Deploy to Staging Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_SSH_USER }}@${{ secrets.STAGING_SSH_HOST_IP }} << 'EOF'
            cd ${{ secrets.STAGING_APP_PATH }}  # Navigate to the staging folder
            
            git fetch origin # Fetch the latest version
            git reset --hard origin/main  # Reset to the latest commit on main branch
            git pull origin main  # Pull the latest changes from main branch
            # git clean -f # Clean the file system
            
            composer install  # Install dependencies
            # php artisan migrate:fresh # First time installation
            # php artisan db:seed
            # php artisan migrate:refresh --step=10
            # php artisan migrate --force  # Migrate the database

            php artisan optimize:clear  # Clear caches
            php artisan migrate --seed  # Migrate and seed the database
            php artisan cache:clear  # Clear the cache
            php artisan view:clear  # Clear the view cache
            php artisan route:cache  # Clear the route cache
            php artisan optimize  # Optimize the application

            npm install  # Install dependencies
            npm run build  # Build the Node app
          EOF
